# Generated by Django 2.2 on 2021-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='barcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
