# Generated by Django 2.2 on 2021-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='barcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
