# Generated by Django 2.2 on 2021-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
