# Generated by Django 2.2 on 2021-12-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20211207_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
