# Generated by Django 2.2 on 2021-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='token',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
